Debug 6

diff --git a/.gitlab/common.yml b/.gitlab/common.yml
--- a/.gitlab/common.yml
+++ b/.gitlab/common.yml
@@ -300,17 +300,18 @@
     - echo "docker ps output"
     - docker ps
     - export ANCESTOR_CONTAINERS=$(docker ps -a --filter "ancestor=${FULL_IMAGE_NAME}" --format "{{.Names}}") 
-    - echo "Containers are ${ANCESTOR_CONTAINERS}"
+    - VAR="Test"
+    - echo "This is failing: ${VAR}"
     - echo "Matching against: ${COMPONENT}-${BRANCH_LOWER}"
-      #    - export MATCHING_CONTAINERS=$( echo "$ANCESTOR_CONTAINERS" | grep "${COMPONENT}-${BRANCH_LOWER}" || echo "")
-      #    - echo "Matching containers are: $MATCHING_CONTAINERS" 
-      #    - if [ -z "$MATCHING_CONTAINERS" ]; then
-      #        echo "No matching containers found for image ${FULL_IMAGE_NAME} and component ${COMPONENT}-${BRANCH_LOWER}";
-      #      else
-      #        docker logs $MATCHING_CONTAINERS;
-      #      fi
-      #  rules:
-      #    - when: always
+    - export MATCHING_CONTAINERS=$( echo "$ANCESTOR_CONTAINERS" | grep "${COMPONENT}-${BRANCH_LOWER}" || echo "")
+    - echo "Matching containers are: $MATCHING_CONTAINERS" 
+    - if [ -z "$MATCHING_CONTAINERS" ]; then
+        echo "No matching containers found for image ${FULL_IMAGE_NAME} and component ${COMPONENT}-${BRANCH_LOWER}";
+      else
+        docker logs $MATCHING_CONTAINERS;
+      fi
+  rules:
+    - when: always
 
 # In the case that we are not needing to actually rebuild the image we want to
 # retag the image that already exists in harbor with the current commit, this
