Ensure output from failed ci harbor check script

diff --git a/.gitlab/common.yml b/.gitlab/common.yml
--- a/.gitlab/common.yml
+++ b/.gitlab/common.yml
@@ -59,7 +59,9 @@
           first_iteration="FALSE"
         fi
       done
-    - cat "./harbor_check.log"
+  after_script:
+    # Needed if the harbor check script errors out.
+    - if [ -f "./harbor_check.log" ]; then cat "./harbor_check.log"; fi;
 
 .docker_build_script:
   script:
@@ -76,27 +78,28 @@
     - docker push "${REGISTRY}/${PROJECT}/${DATAFED_HARBOR_REPOSITORY}:$CI_COMMIT_SHA"
     - first_iteration="TRUE"
     - artifact_count="0"
-    - |
-      while [ "$artifact_count" == "0" ]; do
-        artifact_count=$(./scripts/ci_harbor_artifact_count.sh -r "${DATAFED_HARBOR_REPOSITORY}")
-        error_code="$?"
-        if [ "$error_code" != "0" ]
-        then
-          echo "Error encountered in ci_harbor_artifact_count $error_code"
-          cat "./harbor_check.log"
-          exit 1
-        fi;
-        echo "Artifact missing from harbor..."
-        docker push "${REGISTRY}/${PROJECT}/${DATAFED_HARBOR_REPOSITORY}:latest"
-        docker push "${REGISTRY}/${PROJECT}/${DATAFED_HARBOR_REPOSITORY}:$CI_COMMIT_SHA"
-        if [ "$first_iteration" == "FALSE" ]
-        then
-          sleep 5  # Optional: Add a sleep to avoid busy waiting 
-        else
-          first_iteration="FALSE"
-        fi
-      done
-    - cat "./harbor_check.log"
+    - while [ "$artifact_count" == "0" ]; do
+    -   artifact_count=$(./scripts/ci_harbor_artifact_count.sh -r "${DATAFED_HARBOR_REPOSITORY}")
+    -   error_code="$?"
+    -   if [ "$error_code" != "0" ]
+    -   then
+    -     echo "Error encountered in ci_harbor_artifact_count $error_code"
+    -     cat "./harbor_check.log"
+    -     exit 1
+    -   fi;
+    -   echo "Artifact missing from harbor..."
+    -   docker push "${REGISTRY}/${PROJECT}/${DATAFED_HARBOR_REPOSITORY}:latest"
+    -   docker push "${REGISTRY}/${PROJECT}/${DATAFED_HARBOR_REPOSITORY}:$CI_COMMIT_SHA"
+    -   if [ "$first_iteration" == "FALSE" ]
+    -   then
+    -     sleep 5  # Optional: Add a sleep to avoid busy waiting 
+    -   else
+    -     first_iteration="FALSE"
+    -   fi
+    - done
+  after_script:
+    # Needed if the harbor check script errors out.
+    - if [ -f "./harbor_check.log" ]; then cat "./harbor_check.log"; fi;
 
 .error_logs_client_end_to_end:
   stage: log
@@ -141,7 +144,6 @@
     -     first_iteration="FALSE"
     -   fi
     - done
-    - cat "./harbor_check.log"
   after_script:
     # Needed if the harbor check script errors out.
     - if [ -f "./harbor_check.log" ]; then cat "./harbor_check.log"; fi;
