Add error code check to retag template (gitlab)

diff --git a/.gitlab/common.yml b/.gitlab/common.yml
--- a/.gitlab/common.yml
+++ b/.gitlab/common.yml
@@ -78,11 +78,12 @@
       first_iteration="TRUE"
       artifact_count="0"
       while [ "$artifact_count" == "0" ]; do
-        artifact_count=$(./scripts/ci_harbor_artifact_count.sh -r ${DATAFED_HARBOR_REPOSITORY})
+        artifact_count=$(./scripts/ci_harbor_artifact_count.sh -r "${DATAFED_HARBOR_REPOSITORY}")
         error_code="$?"
         if [ "$error_code" != "0" ]
         then
-          echo "error"
+          echo "Error encountered in ci_harbor_artifact_count $error_code"
+          cat "./harbor_check.log"
           exit 1
         fi;
         echo "Artifact missing from harbor..."
@@ -122,7 +123,16 @@
     - docker push "${REGISTRY}/${PROJECT}/${DATAFED_HARBOR_REPOSITORY}:$CI_COMMIT_SHA"
     - |
       first_iteration="TRUE"
-      while [ "$(./scripts/ci_harbor_artifact_count.sh -r ${DATAFED_HARBOR_REPOSITORY})" == "0" ]; do
+      artifact_count="0"
+      while [ "$artifact_count" == "0" ]; do
+        artifact_count=$(./scripts/ci_harbor_artifact_count.sh -r "${DATAFED_HARBOR_REPOSITORY}")
+        error_code="$?"
+        if [ "$error_code" != "0" ]
+        then
+          echo "Error encountered in ci_harbor_artifact_count $error_code"
+          cat "./harbor_check.log"
+          exit 1
+        fi;
         echo "Artifact missing from harbor..."
         docker push "${REGISTRY}/${PROJECT}/${DATAFED_HARBOR_REPOSITORY}:$CI_COMMIT_SHA"
         if [ "$first_iteration" == "FALSE" ]
