style: applied formatting to all yml files.

diff --git a/.gitlab/build/force_build_dependencies_image.yml b/.gitlab/build/force_build_dependencies_image.yml
--- a/.gitlab/build/force_build_dependencies_image.yml
+++ b/.gitlab/build/force_build_dependencies_image.yml
@@ -1,35 +1,35 @@
 ---
 stages:
-  - build
+    - build
 
 build-dependencies:
-  stage: build
-  tags:
-    - ci-datafed-core
-    - docker
-  script:
-    - |
-      # Variables you need set in CI/CD Settings or here
-      DOWNSTREAM_PROJECT_ID="19248"      # Numeric GitLab project ID
-      cd "$CI_PROJECT_DIR/external/DataFedDependencies"
-      #DOWNSTREAM_REF=$(git branch --show-current)   # Branch to run pipeline on
-      cd "$CI_PROJECT_DIR"
-      DOWNSTREAM_SHA=$(git submodule status ./external/DataFedDependencies/ | awk '{print $1}')   # Commit SHA to trigger on
-      # Remove leading '-' if one exists
-      DOWNSTREAM_SHA=${DOWNSTREAM_SHA#-}
-      echo "DataFedDependencies current commit: $DOWNSTREAM_SHA"
-      # Trigger the downstream pipeline
-      echo "Triggering downstream pipeline... $CI_API_V4_URL/projects/$DATAFED_DEPENDENCIES_GITLAB_PROJECT_ID/trigger/pipeline"
-      #-F "token=$GITLAB_DATAFED_DEPENDENCIES_REPO_API_TOKEN" \
-      # PIPELINE=$(curl --silent --fail --show-error -X POST \
-      #         -F "token=$CI_JOB_TOKEN" \
-      #         -F "ref=main" \
-      #         --form "variables[COMMIT_SHA]=$DOWNSTREAM_SHA" \
-      #         "$CI_API_V4_URL/projects/$DATAFED_DEPENDENCIES_GITLAB_PROJECT_ID/trigger/pipeline" )
-      # PIPELINE_ID=$(echo "$PIPELINE" | jq -r '.id')
-      # if [ "$PIPELINE_ID" = "null" ] || [ -z "$PIPELINE_ID" ]; then
-      #   echo "❌ Failed to create pipeline"
-      #   echo "$PIPELINE"
-      #   exit 1
-      # fi
-      # echo "✅ Triggered pipeline $PIPELINE_ID for commit $DOWNSTREAM_SHA"
+    stage: build
+    tags:
+        - ci-datafed-core
+        - docker
+    script:
+        - |
+            # Variables you need set in CI/CD Settings or here
+            DOWNSTREAM_PROJECT_ID="19248"      # Numeric GitLab project ID
+            cd "$CI_PROJECT_DIR/external/DataFedDependencies"
+            #DOWNSTREAM_REF=$(git branch --show-current)   # Branch to run pipeline on
+            cd "$CI_PROJECT_DIR"
+            DOWNSTREAM_SHA=$(git submodule status ./external/DataFedDependencies/ | awk '{print $1}')   # Commit SHA to trigger on
+            # Remove leading '-' if one exists
+            DOWNSTREAM_SHA=${DOWNSTREAM_SHA#-}
+            echo "DataFedDependencies current commit: $DOWNSTREAM_SHA"
+            # Trigger the downstream pipeline
+            echo "Triggering downstream pipeline... $CI_API_V4_URL/projects/$DATAFED_DEPENDENCIES_GITLAB_PROJECT_ID/trigger/pipeline"
+            #-F "token=$GITLAB_DATAFED_DEPENDENCIES_REPO_API_TOKEN" \
+            # PIPELINE=$(curl --silent --fail --show-error -X POST \
+            #         -F "token=$CI_JOB_TOKEN" \
+            #         -F "ref=main" \
+            #         --form "variables[COMMIT_SHA]=$DOWNSTREAM_SHA" \
+            #         "$CI_API_V4_URL/projects/$DATAFED_DEPENDENCIES_GITLAB_PROJECT_ID/trigger/pipeline" )
+            # PIPELINE_ID=$(echo "$PIPELINE" | jq -r '.id')
+            # if [ "$PIPELINE_ID" = "null" ] || [ -z "$PIPELINE_ID" ]; then
+            #   echo "❌ Failed to create pipeline"
+            #   echo "$PIPELINE"
+            #   exit 1
+            # fi
+            # echo "✅ Triggered pipeline $PIPELINE_ID for commit $DOWNSTREAM_SHA"
