debug: trying to find invalid yaml.

diff --git a/.gitlab/build/force_build_dependencies_image.yml b/.gitlab/build/force_build_dependencies_image.yml
--- a/.gitlab/build/force_build_dependencies_image.yml
+++ b/.gitlab/build/force_build_dependencies_image.yml
@@ -21,15 +21,15 @@ build-dependencies:
       # Trigger the downstream pipeline
       echo "Triggering downstream pipeline... $CI_API_V4_URL/projects/$DATAFED_DEPENDENCIES_GITLAB_PROJECT_ID/trigger/pipeline"
       #-F "token=$GITLAB_DATAFED_DEPENDENCIES_REPO_API_TOKEN" \
-      PIPELINE=$(curl --silent --fail --show-error -X POST \
-              -F "token=$CI_JOB_TOKEN" \
-              -F "ref=main" \
-              --form "variables[COMMIT_SHA]=$DOWNSTREAM_SHA" \
-              "$CI_API_V4_URL/projects/$DATAFED_DEPENDENCIES_GITLAB_PROJECT_ID/trigger/pipeline" )
-      PIPELINE_ID=$(echo "$PIPELINE" | jq -r '.id')
-      if [ "$PIPELINE_ID" = "null" ] || [ -z "$PIPELINE_ID" ]; then
-        echo "❌ Failed to create pipeline"
-        echo "$PIPELINE"
-        exit 1
-      fi
-      echo "✅ Triggered pipeline $PIPELINE_ID for commit $DOWNSTREAM_SHA"
+      # PIPELINE=$(curl --silent --fail --show-error -X POST \
+      #         -F "token=$CI_JOB_TOKEN" \
+      #         -F "ref=main" \
+      #         --form "variables[COMMIT_SHA]=$DOWNSTREAM_SHA" \
+      #         "$CI_API_V4_URL/projects/$DATAFED_DEPENDENCIES_GITLAB_PROJECT_ID/trigger/pipeline" )
+      # PIPELINE_ID=$(echo "$PIPELINE" | jq -r '.id')
+      # if [ "$PIPELINE_ID" = "null" ] || [ -z "$PIPELINE_ID" ]; then
+      #   echo "❌ Failed to create pipeline"
+      #   echo "$PIPELINE"
+      #   exit 1
+      # fi
+      # echo "✅ Triggered pipeline $PIPELINE_ID for commit $DOWNSTREAM_SHA"
