refactor: build remove status check.

diff --git a/.gitlab/build/force_build_dependencies_image.yml b/.gitlab/build/force_build_dependencies_image.yml
--- a/.gitlab/build/force_build_dependencies_image.yml
+++ b/.gitlab/build/force_build_dependencies_image.yml
@@ -34,19 +34,19 @@ build-dependencies:
       fi
       echo "✅ Triggered pipeline $PIPELINE_ID for commit $DOWNSTREAM_SHA"
       # Poll until finished
-      STATUS="running"
-      while [ "$STATUS" = "running" ] || [ "$STATUS" = "pending" ]; do
-        sleep 20
-        STATUS=$(curl --silent --fail \
-          --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
-          "$CI_API_V4_URL/projects/$DOWNSTREAM_PROJECT_ID/pipelines/$PIPELINE_ID" \
-          | jq -r '.status')
-        echo "Pipeline $PIPELINE_ID status: $STATUS"
-      done
-      if [ "$STATUS" = "success" ]; then
-        echo "🎉 Downstream pipeline succeeded"
-        exit 0
-      else
-        echo "❌ Downstream pipeline failed with status: $STATUS"
-        exit 1
-      fi
+      # STATUS="running"
+      # while [ "$STATUS" = "running" ] || [ "$STATUS" = "pending" ]; do
+      #   sleep 20
+      #   STATUS=$(curl --silent --fail \
+      #     --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
+      #     "$CI_API_V4_URL/projects/$DOWNSTREAM_PROJECT_ID/pipelines/$PIPELINE_ID" \
+      #     | jq -r '.status')
+      #   echo "Pipeline $PIPELINE_ID status: $STATUS"
+      # done
+      # if [ "$STATUS" = "success" ]; then
+      #   echo "🎉 Downstream pipeline succeeded"
+      #   exit 0
+      # else
+      #   echo "❌ Downstream pipeline failed with status: $STATUS"
+      #   exit 1
+      # fi
